### PR TITLE
WatchFace

### PR DESCRIPTION
**Pull request by Mimkemartens**
PointerAndNumbers

### CODE REVIEW

**Comment by lrenzo740** [comment]
do you have the complete android studio folders and files so that we can get started?

**Comment by Mimkemartens** [comment]
The project is based on a simple watchface. If you start a new project in Android Studio, a project for smartwatches, and don't use the completely empty preselection, but rather the next template, then you can transfer the files to this project structure.



 
 
  Am Fr., Nov. 15, 2024 at 16:14 schrieb ***@***.***>:   


do you have the complete android studio folders and files so that we can get started?

**Comment by lrenzo740** [comment]
alright I get it.


Noong Sab, Nob 16, 2024 nang 12:29 AM, sinulat ni Mimkemartens <
***@***.***> ang:

**Comment by Mimkemartens** [comment]
Let me know if you can complete the modernization and add an interface for a smartwatch. If you can do that, please let me know how much time it will take you to do it, a rough estimate, and how much money you would like to have for it - approximately.The AI ​​Claude and subsequently the Studio Bot recommended implementing the extension for the smartphone in the original Watchface project. To do this, an extension is made in Android Studio via “File” > “New” > “New Module”. This is now the “mobile” folder in the Watchface GitHub repository.


 
 
  Am Sa., Nov. 16, 2024 at 0:10 schrieb ***@***.***>:   

alright I get it.


Noong Sab, Nob 16, 2024 nang 12:29 AM, sinulat ni Mimkemartens <
***@***.***> ang:

**Comment by Mimkemartens** [comment]
I'm trying to upload the entire project to a new repository on GitHub. This is how the AI Copilot could be used as well. I'll let you know if I was successful.


 
 
  Am Sa., Nov. 16, 2024 at 0:10 schrieb ***@***.***>:   

alright I get it.


Noong Sab, Nob 16, 2024 nang 12:29 AM, sinulat ni Mimkemartens <
***@***.***> ang:

**Comment by lrenzo740** [comment]
Do you have a discord so that we can discuss our concerns easily? coz it’s
really hard to communicate through email if it’s okay with you. I will
check the dependencies and install first the required library then i’ll
tell you the time estimate. However, just to give you an heads-ups, we will
be through a tough adventure so might as well we will have some
feed-backing and communication preferably discord.

**Comment by Mimkemartens** [comment]
The link for Google Drive:
https://drive.google.com/drive/folders/1SMzGLDJhzfn5coIowTfBBWFx2heDKZHa?usp=drive_link


Am Sa., 16. Nov. 2024 um 02:14 Uhr schrieb lrenzo740 <
***@***.***>:

**Comment by Mimkemartens** [comment]
All those pictures belong in the folder
AndroidStudioProjects\TikTak\app\src\main\res\drawable

Am Sa., 16. Nov. 2024 um 02:14 Uhr schrieb lrenzo740 <
***@***.***>:

**Comment by lrenzo740** [comment]
yeah I did checked on the folders but the picture preview_digital did not exist in the res file

**Pull request merged**
